# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdabedc2925bc330292ffdb0e1745dd1b87af0071238e0cc9d9a7efd5edf000a0e73d5abb0afb0f66d246828d65f7d6feff35a61a491e25235fb37ee6b5e2f67

test:
  secret_key_base: a86496dbf5757279589b0b01929f48334a47d3274ee674a06a90291214902b8d4c0af5d4f9792ac0e6973cc9037253024cded9bc980e25e9579f2c7e1513f74a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
